### PR TITLE
Added feature (Shows the latest orders from stocks ran on the algorithm through a watchlist)

### PR DESCRIPTION
**Pull request by uatemycookie22**
I have added this new feature to iterate through a watchlist of stocks and return the latest order (which is on the latest date of the given stock history) for each of the stocks. Entering 'today' when asked for a ticket prints this list of orders. The 'Current performance' that is printed with the order is simply a percentage change between the entry price and the latest value of the portfolio that followed the algorithm.

Code:
```Python
watchlist = ['BABA', 'IBM', 'PEN', 'GOOG', 'SPCE', 'AMD', 'NIO', 'ARKG', 'PENN', 'MRNA', 'WMT', 'AAPL', 'SBUX', 'NKE', 'SNE']
for ticker in watchlist:
        portfolio, entry_price, control_value, algo_value, prices, days = run_algo(ticker, starting_capital, starting_shares)
        order_today = portfolio.Orders[days-1]
        highlight_color = order_today['Type'] == "Buy" and 'green' or order_today['Type'] == "Sell" and 'red' or 'white'
        performance = math.floor( (algo_value-entry_price)/entry_price*100 )
        print(ticker,colored( order_today, highlight_color), "Current performance: "+ (algo_value >= entry_price and "+%" or algo_value < entry_price and "-%")+ str(performance))
```
Output:
```
BABA {'Type': 'Buy', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%183
IBM {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%9
PEN {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%270
GOOG {'Type': 'Sell', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%77
SPCE {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%230
AMD {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%1020
NIO {'Type': 'Sell', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%573
ARKG {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%141
PENN {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%501
MRNA {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%460
WMT {'Type': 'Sell', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%103
AAPL {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%389
SBUX {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%141
NKE {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%148
SNE {'Type': 'Hold', 'Day': Timestamp('2020-12-23 00:00:00')} Current performance: +%292
```

### CODE REVIEW

**Comment by ryantcullen** [comment]
Cool! Would you mind submitting this on a new branch? If you do I will accept.

**Comment by uatemycookie22** [comment]
> Cool! Would you mind submitting this on a new branch? If you do I will accept.

Submit this on a new branch? I'm sorry I'm still a little unfamiliar with GitHub. Do you mean making a new branch on my fork and making a new pull request from that?

**Comment by ryantcullen** [comment]
Yep that's what I mean.

**Comment by ryantcullen** [comment]
> > Cool! Would you mind submitting this on a new branch? If you do I will accept.
> 
> 
> 
> Submit this on a new branch? I'm sorry I'm still a little unfamiliar with GitHub. Do you mean making a new branch on my fork and making a new pull request from that?

yes.

**Pull request closed without merging**
